name: sloc

# We want the workflow to run on every push to any branch
# PRs would need to be handled separately due to how changed
# files are determined
on:
  push:
    paths:
      - customers/**
    branch:
      - '*'

jobs:
  changed_files:
    name: Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changed_files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            customers/*.py

      - name: Print Changed Files
        run: echo "${{ steps.changed_files.outputs.files }}"