name: sloc

# We want the workflow to run on every push to any branch
# PRs would need to be handled separately due to how changed
# files are determined
on:
  push:
    paths:
      - customers/**
    branch:
      - '*'

jobs:
  changed_files:
    name: Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changed_customer_files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            customers/*.py

      - outputs:
          all_changed_files: ${{ steps.changed_customer_files.outputs.all_changed_files }}
    
  line_counts:
    name: Line Counts
    needs: changed_files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Line Counts
        id: line_counts
        uses: tj-actions/sloc@v2.0.0
        with:
          files: ${{ needs.changed_files.outputs.all_changed_files }}

      - name: Line Counts Output
        run: echo "${{ steps.line_counts.outputs.line_counts }}"